name: hello_kitty_water_reminder
description: "Um aplicativo fofo temático da Hello Kitty para lembrar de beber água"
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/fonts/Nunito-Regular.ttf
  #       - asset: assets/fonts/Nunito-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/kitty.png"
  adaptive_icon_background: "#FFB6C1"
  adaptive_icon_foreground: "assets/icons/kitty.png"